# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3-2-gcd0df74
_src_path: git+https://git.sr.ht/~dmerej/copier-python
author_email: dimitri@dmerej.info
author_name: Dimitri Merejkowsky
package_import_name: cli_ui
project_description: Build Nice User Interfaces In The Terminal
project_name: cli-ui
project_version: 0.14.0
